import fs from "node:fs";
import { homedir } from "node:os";
import { dirname, join, relative, sep } from "node:path";
import { HunkUserError } from "../run/errors";
import {
  type BundledSkillName,
  readBundledSkillDocument,
  resolveUserConfigDir,
} from "../run/paths";

/**
 * Runs `hunk skill install`: writes a thin pointer skill into a coding agent's skill directory.
 *
 * The installed file is deliberately not a copy of the bundled skill. It carries only the
 * frontmatter an agent needs to decide when to load it (`name` and `description`, read from the
 * bundled document at install time) and a body that tells the agent to run `hunk skill show` for
 * the real instructions. The installed Hunk binary therefore stays the single owner of the skill
 * text, and upgrading Hunk never leaves a stale copy behind in an agent's directory.
 *
 * Every agent host is one row in `AGENT_SKILL_HOSTS`: where it reads user-wide skills and where
 * it reads repository skills. Filesystem access, the environment, the home directory, and the
 * bundled skill text all arrive through `AgentSkillInstallIo` so tests run against a scratch tree.
 */

/** Marker every generated pointer skill carries so reinstalls can tell their own files apart. */
export const AGENT_SKILL_STUB_MARKER = "<!-- generated by `hunk skill install` -->";

/**
 * Report whether a SKILL.md has the exact shape `renderAgentSkillStub` writes: a frontmatter block,
 * one blank line, then the marker. A hand-written skill that merely quotes the marker somewhere in
 * its body is not Hunk's to overwrite, so the position matters, not just the presence.
 */
export function isHunkGeneratedSkill(document: string) {
  const lines = document.replaceAll("\r\n", "\n").split("\n");
  if (lines[0] !== "---") {
    return false;
  }
  const closing = lines.indexOf("---", 1);
  return (
    closing !== -1 && lines[closing + 1] === "" && lines[closing + 2] === AGENT_SKILL_STUB_MARKER
  );
}

/** Inputs a host needs to resolve its user-wide skills directory. */
interface AgentSkillHostContext {
  env: NodeJS.ProcessEnv;
  home: string;
}

/** One coding agent Hunk can install a pointer skill for. */
export interface AgentSkillHost {
  /** Value accepted by `--agent`. */
  readonly id: string;
  /** Product name shown in output and docs. */
  readonly label: string;
  /** Other spellings `--agent` accepts for this host. */
  readonly aliases?: readonly string[];
  /** Directory holding `<skill>/SKILL.md` for every project on this machine. */
  readonly userSkillsDir: (context: AgentSkillHostContext) => string;
  /** Directory, relative to a repository root, holding that repository's skills. */
  readonly projectSkillsDir: string;
}

/** Resolve `$XDG_CONFIG_HOME`-style config roots the way Hunk resolves its own. */
function configDir(context: AgentSkillHostContext) {
  return resolveUserConfigDir(context.env) ?? join(context.home, ".config");
}

/**
 * Agents Hunk knows how to install into, in the order `--help` lists them.
 *
 * Several hosts also read the shared `.agents/skills` convention, so `agents` installs there once
 * for any agent that follows it instead of writing one copy per product.
 */
export const AGENT_SKILL_HOSTS = [
  {
    id: "claude",
    label: "Claude Code",
    aliases: ["claude-code"],
    userSkillsDir: ({ env, home }) =>
      join(env.CLAUDE_CONFIG_DIR || join(home, ".claude"), "skills"),
    projectSkillsDir: join(".claude", "skills"),
  },
  {
    id: "codex",
    label: "Codex",
    userSkillsDir: ({ env, home }) => join(env.CODEX_HOME || join(home, ".codex"), "skills"),
    projectSkillsDir: join(".agents", "skills"),
  },
  {
    id: "opencode",
    label: "opencode",
    userSkillsDir: (context) => join(configDir(context), "opencode", "skills"),
    projectSkillsDir: join(".opencode", "skills"),
  },
  {
    id: "cursor",
    label: "Cursor",
    userSkillsDir: ({ home }) => join(home, ".cursor", "skills"),
    projectSkillsDir: join(".cursor", "skills"),
  },
  {
    id: "amp",
    label: "Amp",
    userSkillsDir: (context) => join(configDir(context), "agents", "skills"),
    projectSkillsDir: join(".agents", "skills"),
  },
  {
    id: "copilot",
    label: "GitHub Copilot",
    aliases: ["github-copilot"],
    userSkillsDir: ({ home }) => join(home, ".copilot", "skills"),
    projectSkillsDir: join(".github", "skills"),
  },
  {
    id: "agents",
    label: "any agent reading .agents/skills",
    userSkillsDir: ({ home }) => join(home, ".agents", "skills"),
    projectSkillsDir: join(".agents", "skills"),
  },
] as const satisfies readonly AgentSkillHost[];

export type AgentSkillHostId = (typeof AGENT_SKILL_HOSTS)[number]["id"];

/** `--agent` values, in the order help and error messages list them. */
export const AGENT_SKILL_HOST_IDS: readonly AgentSkillHostId[] = AGENT_SKILL_HOSTS.map(
  (host) => host.id,
);

/** One known host, typed by its literal id so callers can carry the id through command inputs. */
export type ResolvedAgentSkillHost = AgentSkillHost & { readonly id: AgentSkillHostId };

/** Resolve one user-supplied `--agent` value, or nothing when it names no known host. */
export function resolveAgentSkillHost(value: string): ResolvedAgentSkillHost | undefined {
  const normalized = value.trim().toLowerCase();
  return (AGENT_SKILL_HOSTS as readonly ResolvedAgentSkillHost[]).find(
    (host) => host.id === normalized || host.aliases?.includes(normalized),
  );
}

/** Join ids into the "`a`, `b`, and `c`" phrasing the error messages use. */
export function listAgentSkillHostIds() {
  const quoted = AGENT_SKILL_HOST_IDS.map((id) => `\`${id}\``);
  return `${quoted.slice(0, -1).join(", ")}, and ${quoted.at(-1)}`;
}

/** Whether the pointer lands in the user's home or the current repository. */
export type AgentSkillScope = "user" | "project";

export interface AgentSkillInstallInput {
  /** Bundled skill the pointer loads. */
  skill: BundledSkillName;
  /** Hosts to install into; at least one. */
  agents: AgentSkillHostId[];
  scope: AgentSkillScope;
  /** Replace an existing SKILL.md that Hunk did not generate. */
  force: boolean;
}

/** Frontmatter fields the pointer copies so the agent triggers on the same conditions. */
export interface SkillFrontmatter {
  name: string;
  description: string;
}

/**
 * Read `name` and `description` from a SKILL.md frontmatter block.
 *
 * Bundled skills keep both values on one line each, so a line-oriented scan is enough; a document
 * missing either field is a packaging bug and fails loudly rather than installing a blank pointer.
 */
export function parseSkillFrontmatter(document: string): SkillFrontmatter {
  const lines = document.replaceAll("\r\n", "\n").split("\n");
  if (lines[0] !== "---") {
    throw new Error("Bundled skill is missing its frontmatter block.");
  }

  const fields: Partial<SkillFrontmatter> = {};
  for (const line of lines.slice(1)) {
    if (line === "---") {
      break;
    }
    const separator = line.indexOf(":");
    if (separator === -1) {
      continue;
    }
    const key = line.slice(0, separator).trim();
    const value = line.slice(separator + 1).trim();
    if (key === "name" || key === "description") {
      fields[key] = value;
    }
  }

  if (!fields.name || !fields.description) {
    throw new Error("Bundled skill frontmatter must declare both name and description.");
  }

  return { name: fields.name, description: fields.description };
}

/**
 * Render the pointer SKILL.md for one bundled skill.
 *
 * The body stays short on purpose: agents load it only after the frontmatter matched, and its one
 * job is to hand off to the installed CLI, which renders the full instructions for its own version.
 */
export function renderAgentSkillStub(frontmatter: SkillFrontmatter) {
  return [
    "---",
    `name: ${frontmatter.name}`,
    `description: ${frontmatter.description}`,
    "---",
    "",
    AGENT_SKILL_STUB_MARKER,
    "",
    `# ${frontmatter.name}`,
    "",
    "This file is a pointer. The instructions live in the installed `hunk` CLI so they always match its version.",
    "",
    "Before anything else, load them and follow them:",
    "",
    "```bash",
    `hunk skill show ${frontmatter.name}`,
    "```",
    "",
    "If `hunk` is not on PATH, ask the user to install Hunk first: https://hunk.dev/docs/start/install/",
    "",
  ].join("\n");
}

/** Filesystem, environment, and output seams `hunk skill install` runs through. */
export interface AgentSkillInstallIo {
  stdout: (text: string) => void;
  env?: NodeJS.ProcessEnv;
  cwd?: string;
  home?: string;
  /** Bundled skill text; defaults to the document shipped beside this binary. */
  readBundledSkill?: (name: BundledSkillName) => string;
  readFile?: (path: string) => string | undefined;
  writeFile?: (path: string, text: string) => void;
  /** What one path is without following links; defaults to `lstat`. */
  inspectPath?: (path: string) => PathKind;
}

/** What a path is on disk, as `lstat` reports it, so links are seen rather than followed. */
export type PathKind = "missing" | "file" | "directory" | "symlink" | "other";

/** One pointer file the command decided to write, before touching the filesystem. */
export interface AgentSkillInstallTarget {
  host: AgentSkillHost;
  path: string;
}

/** Resolve where each requested host keeps skills for the requested scope. */
export function planAgentSkillTargets(
  input: Pick<AgentSkillInstallInput, "skill" | "agents" | "scope">,
  context: AgentSkillHostContext & { cwd: string },
): AgentSkillInstallTarget[] {
  const targets: AgentSkillInstallTarget[] = [];
  const seen = new Set<string>();
  for (const id of input.agents) {
    const host = resolveAgentSkillHost(id);
    if (!host) {
      throw new HunkUserError(`Unknown agent "${id}". Agents are ${listAgentSkillHostIds()}.`);
    }
    const skillsDir =
      input.scope === "project"
        ? join(context.cwd, host.projectSkillsDir)
        : host.userSkillsDir(context);
    const path = join(skillsDir, input.skill, "SKILL.md");
    // Codex, Amp, and the generic host share `.agents/skills`; write that pointer once.
    if (seen.has(path)) {
      continue;
    }
    seen.add(path);
    targets.push({ host, path });
  }
  return targets;
}

/** Read one file, or nothing when it does not exist. */
function readFileIfPresent(path: string) {
  try {
    return fs.readFileSync(path, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return undefined;
    }
    throw error;
  }
}

/** Classify one path with `lstat`, so a link is reported as a link rather than as its target. */
function inspectPathKind(path: string): PathKind {
  let stat: fs.Stats;
  try {
    stat = fs.lstatSync(path);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      return "missing";
    }
    throw error;
  }
  if (stat.isSymbolicLink()) {
    return "symlink";
  }
  if (stat.isDirectory()) {
    return "directory";
  }
  return stat.isFile() ? "file" : "other";
}

/**
 * Refuse a project-scoped target that a checkout could redirect through a symlink.
 *
 * Every path component below the repository root is repository content, so a cloned tree can
 * make `.claude/skills` (or the SKILL.md itself) a link to somewhere in the user's home and turn
 * this write into an overwrite outside the repository. Walking the components with `lstat` and
 * stopping at the first missing one catches a link at any depth without following it. User-scoped
 * targets are not checked: their directories belong to the user, who may well symlink them into a
 * dotfiles checkout on purpose. As with Hunk's workspace write guard, this keeps the tree's own
 * layout honest rather than defending against a racing local attacker.
 */
function assertProjectTargetContained(
  root: string,
  path: string,
  inspectPath: (path: string) => PathKind,
) {
  const segments = relative(root, path).split(sep);
  let current = root;
  for (const segment of segments) {
    current = join(current, segment);
    const kind = inspectPath(current);
    if (kind === "missing") {
      return;
    }
    if (kind === "symlink") {
      throw new HunkUserError(
        `${current} is a symlink; project skill installs refuse to follow links out of the repository.`,
        ["Install with the default user scope, or replace the link with a real directory."],
      );
    }
  }
}

/** Write one file, creating its directories. */
function writeFileWithDirs(path: string, text: string) {
  fs.mkdirSync(dirname(path), { recursive: true });
  fs.writeFileSync(path, text);
}

/** Resolve the home directory from the environment first so tests and sandboxes can redirect it. */
function resolveHome(env: NodeJS.ProcessEnv, fallback?: string) {
  return env.HOME || env.USERPROFILE || fallback || homedir();
}

/** Install pointer skills for every requested agent and report each path written. */
export async function runAgentSkillInstallCommand(
  input: AgentSkillInstallInput,
  io: AgentSkillInstallIo,
): Promise<number> {
  const env = io.env ?? process.env;
  const cwd = io.cwd ?? process.cwd();
  const home = resolveHome(env, io.home);
  const readBundledSkill = io.readBundledSkill ?? readBundledSkillDocument;
  const readFile = io.readFile ?? readFileIfPresent;
  const writeFile = io.writeFile ?? writeFileWithDirs;
  const inspectPath = io.inspectPath ?? inspectPathKind;

  const frontmatter = parseSkillFrontmatter(readBundledSkill(input.skill));
  const stub = renderAgentSkillStub(frontmatter);
  const targets = planAgentSkillTargets(input, { env, home, cwd });

  // Check every target before writing any, so a refusal leaves no half-installed set behind.
  for (const target of targets) {
    if (input.scope === "project") {
      assertProjectTargetContained(cwd, target.path, inspectPath);
    }
    const existing = readFile(target.path);
    if (existing !== undefined && !isHunkGeneratedSkill(existing) && !input.force) {
      throw new HunkUserError(`${target.path} already exists and was not generated by Hunk.`, [
        "Re-run with --force to replace it, or remove the file first.",
      ]);
    }
  }

  for (const target of targets) {
    writeFile(target.path, stub);
    io.stdout(`Installed ${frontmatter.name} for ${target.host.label}\n  ${target.path}\n`);
  }

  io.stdout(
    `\nThe skill loads its instructions from \`hunk skill show ${frontmatter.name}\`, so it stays current across Hunk upgrades.\n`,
  );
  return 0;
}
