import { describe, expect, it } from "bun:test";
import { classifyNoiseFile, noiseKindLabel } from "./fileClassification";

describe("classifyNoiseFile", () => {
  it("detects lockfiles by basename regardless of directory", () => {
    expect(classifyNoiseFile("bun.lock")).toBe("lockfile");
    expect(classifyNoiseFile("package-lock.json")).toBe("lockfile");
    expect(classifyNoiseFile("apps/web/pnpm-lock.yaml")).toBe("lockfile");
    expect(classifyNoiseFile("Cargo.lock")).toBe("lockfile");
    expect(classifyNoiseFile("backend/go.sum")).toBe("lockfile");
    expect(classifyNoiseFile("Gemfile.lock")).toBe("lockfile");
  });

  it("detects minified bundles and source maps by filename", () => {
    expect(classifyNoiseFile("dist/app.min.js")).toBe("minified");
    expect(classifyNoiseFile("public/styles.min.css")).toBe("minified");
    expect(classifyNoiseFile("dist/app.js.map")).toBe("minified");
  });

  it("detects generated files by well-known path shapes", () => {
    expect(classifyNoiseFile("api/service.pb.go")).toBe("generated");
    expect(classifyNoiseFile("proto/user_pb2.py")).toBe("generated");
    expect(classifyNoiseFile("lib/model.g.dart")).toBe("generated");
    expect(classifyNoiseFile("src/types.generated.ts")).toBe("generated");
  });

  it("detects generated files by content markers in added lines", () => {
    const patch = [
      "+++ b/src/schema.ts",
      "@@ -0,0 +1,2 @@",
      "+// @generated by gql",
      "+export const x = 1;",
    ].join("\n");
    expect(classifyNoiseFile("src/schema.ts", patch)).toBe("generated");
  });

  it("detects generated markers on unchanged context lines", () => {
    const patch = [
      " // Code generated by protoc. DO NOT EDIT.",
      "@@ -1 +1 @@",
      "-const a = 1",
      "+const a = 2",
    ].join("\n");
    expect(classifyNoiseFile("src/gen.ts", patch)).toBe("generated");
  });

  it("ignores markers that only appear on removed lines", () => {
    const patch = ["@@ -1 +1 @@", "-// @generated old header", "+const a = 2"].join("\n");
    expect(classifyNoiseFile("src/app.ts", patch)).toBeNull();
  });

  it("does not treat the +++ header as an added marker", () => {
    const patch = ["+++ b/@generated/file.ts", "@@ -1 +1 @@", "+const a = 1"].join("\n");
    // The path itself is not a known shape and no real added line carries a marker.
    expect(classifyNoiseFile("normal.ts", patch)).toBeNull();
  });

  it("returns null for ordinary source files", () => {
    expect(classifyNoiseFile("src/core/cli.ts")).toBeNull();
    expect(classifyNoiseFile("README.md")).toBeNull();
    expect(classifyNoiseFile("src/app.test.ts", "+const a = 1")).toBeNull();
  });

  it("is case-insensitive for lockfile basenames", () => {
    expect(classifyNoiseFile("CARGO.LOCK")).toBe("lockfile");
  });
});

describe("noiseKindLabel", () => {
  it("maps each kind to a human label", () => {
    expect(noiseKindLabel("lockfile")).toBe("Lockfile");
    expect(noiseKindLabel("minified")).toBe("Minified file");
    expect(noiseKindLabel("generated")).toBe("Generated file");
  });
});
