/**
 * Classify diff files as low-signal "noise" — dependency lockfiles, minified
 * bundles, and machine-generated code — so the review UI can collapse them by
 * default. Agent changesets routinely touch these alongside real edits, and
 * surfacing them at full weight buries the changes a human actually needs to read.
 *
 * Detection is deliberately conservative: filename/basename rules first (cheap,
 * unambiguous), then a capped scan of the patch for well-known generator markers.
 * A false negative just shows a file normally; a false positive only hides it
 * behind a one-key expand, so we err toward the well-established signals.
 */
import { basename } from "node:path";
import type { NoiseKind } from "./types";

/** Dependency lockfiles across ecosystems, matched by lowercased basename. */
const LOCKFILE_NAMES = new Set([
  "package-lock.json",
  "npm-shrinkwrap.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "bun.lock",
  "bun.lockb",
  "deno.lock",
  "cargo.lock",
  "composer.lock",
  "gemfile.lock",
  "poetry.lock",
  "pdm.lock",
  "pipfile.lock",
  "uv.lock",
  "go.sum",
  "packages.lock.json",
  "podfile.lock",
  "mix.lock",
  "flake.lock",
  "gradle.lockfile",
]);

/** Minified or machine-emitted asset filenames (e.g. `app.min.js`, `app.js.map`). */
const MINIFIED_PATTERN = /(\.min\.(js|mjs|cjs|css)|\.(js|mjs|cjs|css)\.map)$/i;

/** Path shapes emitted by common code generators across ecosystems. */
const GENERATED_PATH_PATTERNS: RegExp[] = [
  /\.pb\.go$/i, // protobuf (Go)
  /_pb2\.pyi?$/i, // protobuf (Python)
  /\.pb\.(cc|h)$/i, // protobuf (C++)
  /\.g\.dart$/i, // build_runner (Dart)
  /\.freezed\.dart$/i, // freezed (Dart)
  /\.designer\.cs$/i, // WinForms designer (C#)
  /\.generated\.[a-z]+$/i, // explicit ".generated." convention
];

/** Content markers conventionally embedded at the top of generated files. */
const GENERATED_CONTENT_MARKERS = [
  "@generated",
  "do not edit",
  "code generated by",
  "auto-generated",
  "autogenerated",
  "this file is generated",
];

// Generated markers live near the top of a file, so scanning the first slice of
// the patch is enough and keeps very large diffs cheap.
const MAX_CONTENT_SCAN_LINES = 80;

/** True when a path matches a known generated-artifact filename shape. */
function looksGeneratedByPath(path: string): boolean {
  return GENERATED_PATH_PATTERNS.some((pattern) => pattern.test(path));
}

/**
 * Scan added/context lines near the top of a patch for generator markers.
 * Removed lines and diff transport headers are ignored so a marker only counts
 * when it is part of the file's current content.
 */
function looksGeneratedByContent(patch: string): boolean {
  const lines = patch.split("\n", MAX_CONTENT_SCAN_LINES);

  for (const line of lines) {
    // Only consider added (`+foo`, not the `+++` header) or context (` foo`) lines.
    const isAddition = line[0] === "+" && line[1] !== "+";
    const isContext = line[0] === " ";
    if (!isAddition && !isContext) {
      continue;
    }

    const haystack = line.slice(1).toLowerCase();
    if (GENERATED_CONTENT_MARKERS.some((marker) => haystack.includes(marker))) {
      return true;
    }
  }

  return false;
}

/**
 * Classify one file as review "noise", or return null when it is ordinary code.
 * `patch` is optional; when omitted, only filename-based rules apply.
 */
export function classifyNoiseFile(path: string, patch?: string): NoiseKind | null {
  const name = basename(path).toLowerCase();

  if (LOCKFILE_NAMES.has(name)) {
    return "lockfile";
  }

  if (MINIFIED_PATTERN.test(path)) {
    return "minified";
  }

  if (looksGeneratedByPath(path)) {
    return "generated";
  }

  if (patch && looksGeneratedByContent(patch)) {
    return "generated";
  }

  return null;
}

/** Human-readable label for a noise kind, used in collapsed placeholders. */
export function noiseKindLabel(kind: NoiseKind): string {
  switch (kind) {
    case "lockfile":
      return "Lockfile";
    case "minified":
      return "Minified file";
    case "generated":
      return "Generated file";
  }
}
