import { createHash } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const ASSET_NAMES = ["review.html", "bootstrap.js", "review.css"] as const;

/** Bun's minified browser output is byte-stable on Unix but currently host-dependent on Windows. */
export function canRebuildCanonicalBrowserBundle(platform = process.platform) {
  return platform !== "win32";
}

/** Bundle every transitive React/Pierre/shared source into one deterministic offline script. */
export async function buildBrowserAssetBundle(repoRoot: string, write = true) {
  const result = await Bun.build({
    entrypoints: [path.join(repoRoot, "src", "web", "main.tsx")],
    target: "browser",
    format: "esm",
    minify: true,
    sourcemap: "none",
    splitting: false,
    define: { "process.env.NODE_ENV": JSON.stringify("production") },
  });
  if (!result.success || result.outputs.length !== 1) {
    throw new Error(`Browser asset build failed: ${result.logs.map(String).join("\n")}`);
  }
  const output = await result.outputs[0]!.text();
  const digest = createHash("sha256").update(output).digest("hex");
  const source = `// hunk-web-output:${digest}\n${output}`;
  if (write) writeFileSync(path.join(repoRoot, "src", "browser", "assets", "bootstrap.js"), source);
  return source;
}

/** Rebuild to memory so transitive source changes cannot pass the freshness check. */
export async function assertBrowserBundleCurrent(
  repoRoot: string,
  buildBundle: (root: string, write: boolean) => Promise<string> = buildBrowserAssetBundle,
  platform = process.platform,
) {
  const bundlePath = path.join(repoRoot, "src", "browser", "assets", "bootstrap.js");
  if (!existsSync(bundlePath)) {
    throw new Error("Embedded browser bundle is stale. Run `bun run generate:browser-assets`.");
  }
  // Windows verifies the checked-in module and content digest below, while canonical Unix CI
  // performs the transitive rebuild check that Bun cannot currently reproduce byte-for-byte.
  if (!canRebuildCanonicalBrowserBundle(platform)) return;
  if (readFileSync(bundlePath, "utf8") !== (await buildBundle(repoRoot, false))) {
    throw new Error("Embedded browser bundle is stale. Run `bun run generate:browser-assets`.");
  }
}

/** Render the deterministic TypeScript module embedded by source and compiled builds. */
export function renderBrowserAssetModule(repoRoot: string) {
  const assets = Object.fromEntries(
    ASSET_NAMES.map((name) => [
      name,
      readFileSync(path.join(repoRoot, "src", "browser", "assets", name), "utf8"),
    ]),
  );
  const digest = createHash("sha256").update(JSON.stringify(assets)).digest("hex");
  return (
    `// Generated by scripts/generate-browser-assets.ts. Do not edit.\n` +
    `// oxfmt-ignore\n` +
    `export const BROWSER_ASSET_SOURCE_DIGEST = ${JSON.stringify(digest)};\n` +
    `// oxfmt-ignore\n` +
    `export const EMBEDDED_BROWSER_ASSETS = ${JSON.stringify(assets, null, 2)} as const;\n`
  );
}

/** Fail clearly when embedded files and their generated module disagree. */
export function assertBrowserAssetsCurrent(repoRoot: string) {
  const generatedPath = path.join(repoRoot, "src", "browser", "generated", "assets.ts");
  if (!existsSync(generatedPath)) {
    throw new Error("Missing generated browser assets. Run `bun run generate:browser-assets`.");
  }
  const expected = renderBrowserAssetModule(repoRoot);
  if (readFileSync(generatedPath, "utf8") !== expected) {
    throw new Error("Generated browser assets are stale. Run `bun run generate:browser-assets`.");
  }
  const bundle = readFileSync(
    path.join(repoRoot, "src", "browser", "assets", "bootstrap.js"),
    "utf8",
  );
  const match = bundle.match(/^\/\/ hunk-web-output:([a-f\d]{64})\n/);
  if (
    !match ||
    createHash("sha256").update(bundle.slice(match[0].length)).digest("hex") !== match[1]
  ) {
    throw new Error("Embedded browser bundle is corrupt. Run `bun run generate:browser-assets`.");
  }
}

/** Write the generated browser asset module used for offline serving. */
export function generateBrowserAssets(repoRoot: string) {
  const output = path.join(repoRoot, "src", "browser", "generated", "assets.ts");
  writeFileSync(output, renderBrowserAssetModule(repoRoot));
  return output;
}
