import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

/**
 * Projects `CHANGELOG.md` into the release-notes pages published at hunk.dev/changelog.
 *
 * `CHANGELOG.md` stays the source of truth: this script parses it, groups releases by minor
 * series, merges the hand-authored overlay in `website/releases/notes.json`, and writes committed
 * Markdown into the Starlight docs collection. Nothing here may be hand-edited — regenerate with
 * `bun run generate:changelog` instead.
 *
 * Two invariants keep the output deterministic so `--check` can gate CI without network or Git:
 * release dates live in the committed `website/releases/dates.json`, and a date already recorded
 * there is never recomputed. Only a version with no recorded date consults Git tags, and a version
 * that has neither is rendered as unreleased.
 */

const REPO_ROOT = resolve(import.meta.dir, "..");
const REPO_URL = "https://github.com/modem-dev/hunk";
const SITE_ORIGIN = "https://hunk.dev";
const GENERATED_NOTICE =
  "<!-- GENERATED by `bun run generate:changelog`. Edit CHANGELOG.md or website/releases/notes.json instead. -->";

export const CHANGELOG_SOURCE = resolve(REPO_ROOT, "CHANGELOG.md");
export const RELEASE_NOTES_SOURCE = resolve(REPO_ROOT, "website", "releases", "notes.json");
export const RELEASE_DATES_SOURCE = resolve(REPO_ROOT, "website", "releases", "dates.json");
export const LATEST_RELEASE_PATH = resolve(REPO_ROOT, "website", "releases", "latest.json");
export const CHANGELOG_OUTPUT_DIR = resolve(
  REPO_ROOT,
  "website",
  "src",
  "content",
  "docs",
  "changelog",
);
export const CHANGELOG_FEED_PATH = resolve(REPO_ROOT, "website", "public", "changelog", "rss.xml");

/** One bullet from a release section, with its originating pull request when the entry names one. */
export type ChangeEntry = {
  description: string;
  pullRequest?: number;
};

/** One `### ...` block inside a release, such as `Minor Changes` or `Fixed`. */
export type ChangeSection = {
  title: string;
  entries: ChangeEntry[];
};

/** One `## <version>` block parsed out of `CHANGELOG.md`. */
export type ReleaseEntry = {
  version: string;
  prerelease: boolean;
  /** Date from a legacy `## [x.y.z] - YYYY-MM-DD` heading, when the entry carries one. */
  headingDate?: string;
  /** Raw Markdown of the hand-authored `### Highlights` block. */
  highlights?: string;
  sections: ChangeSection[];
};

/** Every release sharing a `major.minor` line, newest first. */
export type ReleaseSeries = {
  minor: string;
  releases: ReleaseEntry[];
};

/** Hand-authored additions for one minor series. Every field is optional. */
export type SeriesNotes = {
  summary?: string;
  /** Short phrase for the landing-page release ribbon, where a full sentence does not fit. */
  tagline?: string;
  video?: {
    mp4: string;
    webm?: string;
    poster?: string;
    /** ISO 8601 duration such as `PT1M24S`, used for the VideoObject description. */
    duration?: string;
    title?: string;
  };
  links?: { label: string; href: string }[];
};

const MONTHS = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
] as const;

/** Split a version into comparable numeric parts, treating a prerelease as preceding its release. */
function versionSortKey(version: string) {
  const [core = "", pre] = version.split("-", 2);
  const [major = "0", minor = "0", patch = "0"] = core.split(".");
  // A release sorts above its own prereleases, so absent prerelease metadata ranks highest.
  const preRank = pre === undefined ? Number.MAX_SAFE_INTEGER : Number(pre.split(".").at(-1) ?? 0);
  return [Number(major), Number(minor), Number(patch), preRank];
}

/** Order two versions newest first. */
export function compareVersionsDescending(a: string, b: string) {
  const left = versionSortKey(a);
  const right = versionSortKey(b);
  for (let index = 0; index < left.length; index += 1) {
    const difference = (right[index] ?? 0) - (left[index] ?? 0);
    if (difference !== 0) {
      return difference;
    }
  }
  return 0;
}

/** Return the `major.minor` series a version belongs to. */
export function minorSeriesOf(version: string) {
  const [major = "0", minor = "0"] = version.split("-", 1)[0]?.split(".") ?? [];
  return `${major}.${minor}`;
}

/**
 * Strip Changesets' link preamble from one bullet and recover its pull request number.
 *
 * Entries arrive in three shapes across the file's history: `[#711](url) [`sha`](url) - text`,
 * `[`sha`](url) - text` when the change landed without a linked pull request, and the legacy
 * `sha: text`. Anything else is kept verbatim.
 */
export function parseChangeEntry(raw: string): ChangeEntry {
  const text = raw.trim();
  const pullRequestMatch = text.match(/^\[#(\d+)\]\([^)]+\)\s*/);
  let rest = text;
  let pullRequest: number | undefined;
  if (pullRequestMatch?.[1]) {
    pullRequest = Number(pullRequestMatch[1]);
    rest = rest.slice(pullRequestMatch[0].length);
  }

  // Drop any commit links that follow the pull-request link; the description carries the meaning.
  rest = rest.replace(/^(?:\[`[0-9a-f]+`\]\([^)]+\)\s*)+/, "");
  rest = rest.replace(/^-\s+/, "");
  // Legacy entries prefixed a bare short SHA instead of linking it.
  rest = rest.replace(/^[0-9a-f]{7,40}:\s+/, "");

  return pullRequest === undefined
    ? { description: rest.trim() }
    : { description: rest.trim(), pullRequest };
}

/** Collect the `- ` bullets in one section body, joining wrapped continuation lines. */
function parseEntries(body: string): ChangeEntry[] {
  const entries: string[] = [];
  for (const line of body.split("\n")) {
    if (line.startsWith("- ")) {
      entries.push(line.slice(2));
      continue;
    }
    // A non-blank, non-bullet line continues the bullet above it.
    if (line.trim() !== "" && entries.length > 0) {
      entries[entries.length - 1] += ` ${line.trim()}`;
    }
  }
  return entries.map(parseChangeEntry).filter((entry) => entry.description !== "");
}

/**
 * Parse `CHANGELOG.md` into releases, newest first.
 *
 * Handles both formats the file carries: the Changesets output used since 0.16.0 and the
 * Keep a Changelog headings (`## [0.15.3] - 2026-06-13`) used before it.
 */
export function parseChangelog(markdown: string): ReleaseEntry[] {
  const releases: ReleaseEntry[] = [];
  // Split on `## ` headings while keeping each heading with its body.
  const blocks = markdown.split(/^## /m).slice(1);

  for (const block of blocks) {
    const newline = block.indexOf("\n");
    const heading = (newline === -1 ? block : block.slice(0, newline)).trim();
    const body = newline === -1 ? "" : block.slice(newline + 1);

    const legacy = heading.match(/^\[([^\]]+)\]\s*-\s*(\d{4}-\d{2}-\d{2})$/);
    const version = legacy?.[1] ?? heading;
    if (!/^\d+\.\d+\.\d+/.test(version)) {
      continue;
    }

    const sections: ChangeSection[] = [];
    let highlights: string | undefined;
    for (const sectionBlock of body.split(/^### /m).slice(1)) {
      const sectionNewline = sectionBlock.indexOf("\n");
      const title = (
        sectionNewline === -1 ? sectionBlock : sectionBlock.slice(0, sectionNewline)
      ).trim();
      const sectionBody = sectionNewline === -1 ? "" : sectionBlock.slice(sectionNewline + 1);

      if (title === "Highlights") {
        highlights = sectionBody.trim();
        continue;
      }

      const entries = parseEntries(sectionBody);
      // Legacy releases left empty `### Changed` headings behind; drop them rather than render them.
      if (entries.length > 0) {
        sections.push({ title, entries });
      }
    }

    releases.push({
      version,
      prerelease: version.includes("-"),
      ...(legacy?.[2] ? { headingDate: legacy[2] } : {}),
      ...(highlights ? { highlights } : {}),
      sections,
    });
  }

  return releases.sort((a, b) => compareVersionsDescending(a.version, b.version));
}

/** Group parsed releases into minor series, newest series first. */
export function groupIntoSeries(releases: readonly ReleaseEntry[]): ReleaseSeries[] {
  const byMinor = new Map<string, ReleaseEntry[]>();
  for (const release of releases) {
    const minor = minorSeriesOf(release.version);
    const bucket = byMinor.get(minor);
    if (bucket) {
      bucket.push(release);
    } else {
      byMinor.set(minor, [release]);
    }
  }

  return [...byMinor.entries()]
    .map(([minor, entries]) => ({
      minor,
      releases: entries.sort((a, b) => compareVersionsDescending(a.version, b.version)),
    }))
    .sort((a, b) => compareVersionsDescending(`${a.minor}.0`, `${b.minor}.0`));
}

/** Read the committed release-date map, tolerating a missing file on first generation. */
function readDates(): Record<string, string> {
  try {
    return JSON.parse(readFileSync(RELEASE_DATES_SOURCE, "utf8")) as Record<string, string>;
  } catch {
    return {};
  }
}

/** Read the hand-authored overlay, tolerating a missing file. */
function readNotes(): Record<string, SeriesNotes> {
  try {
    return JSON.parse(readFileSync(RELEASE_NOTES_SOURCE, "utf8")) as Record<string, SeriesNotes>;
  } catch {
    return {};
  }
}

/**
 * Resolve the tag date for one version, or `undefined` when Git cannot answer.
 *
 * Shallow clones and tagless checkouts are expected — the committed date map is what makes
 * generation deterministic, and this only ever fills gaps in it.
 */
function tagDate(version: string): string | undefined {
  try {
    const stdout = execFileSync("git", ["log", "-1", "--format=%as", `v${version}`], {
      cwd: REPO_ROOT,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    });
    const date = stdout.trim();
    return /^\d{4}-\d{2}-\d{2}$/.test(date) ? date : undefined;
  } catch {
    return undefined;
  }
}

/**
 * Fill in dates for versions the committed map has not recorded yet.
 *
 * Recorded dates are never recomputed, so regeneration is stable even as tags move between
 * checkouts. Returns the merged map so callers can persist it.
 */
export function resolveDates(
  releases: readonly ReleaseEntry[],
  recorded: Record<string, string>,
  lookup: (version: string) => string | undefined = tagDate,
): Record<string, string> {
  const resolved: Record<string, string> = { ...recorded };
  for (const release of releases) {
    if (resolved[release.version]) {
      continue;
    }
    const date = release.headingDate ?? lookup(release.version);
    if (date) {
      resolved[release.version] = date;
    }
  }
  // Keep the committed file diff-stable regardless of discovery order.
  return Object.fromEntries(
    Object.entries(resolved).sort(([a], [b]) => compareVersionsDescending(a, b)),
  );
}

/** Build the stable in-page anchor for one version, e.g. `0.18.2` becomes `v0-18-2`. */
export function versionAnchor(version: string) {
  return `v${version.replaceAll(".", "-")}`;
}

/** Render `2026-08-16` as `August 16, 2026`. */
export function formatDate(iso: string) {
  const [year, month, day] = iso.split("-");
  const name = MONTHS[Number(month) - 1];
  return name && year && day ? `${name} ${Number(day)}, ${year}` : iso;
}

/**
 * Quote a value as a YAML frontmatter scalar.
 *
 * Prefers single quotes when the value contains double quotes but no single quotes, matching what
 * the repository formatter would rewrite the line to. Generated output has to survive
 * `bun run format` unchanged, or `--check` reports every page as stale.
 */
export function yamlString(value: string) {
  if (value.includes('"') && !value.includes("'")) {
    return `'${value}'`;
  }
  return `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;
}

/**
 * Reduce Markdown prose to plain text for frontmatter descriptions and feed summaries.
 *
 * Only the inline constructs the changelog actually uses are unwrapped; the result is a single
 * line so it can be embedded in YAML and XML without further escaping.
 */
export function toPlainText(markdown: string) {
  return markdown
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1")
    .replaceAll("**", "")
    .replaceAll("`", "")
    .replace(/\s+/g, " ")
    .trim();
}

/** Truncate plain text on a word boundary so descriptions stay within search-result length. */
export function truncate(text: string, limit: number) {
  if (text.length <= limit) {
    return text;
  }
  const clipped = text.slice(0, limit);
  const lastSpace = clipped.lastIndexOf(" ");
  // Always break on a word boundary when the clip contains one; a mid-word cut reads as corruption
  // in a search result or feed summary.
  const body = lastSpace > 0 ? clipped.slice(0, lastSpace) : clipped;
  return `${body.replace(/[,;:.\s]+$/, "")}…`;
}

/**
 * Split a `### Highlights` block into its lead paragraph and the bullets beneath it.
 *
 * The lead paragraph becomes the page's opening summary, so the rendered Highlights section keeps
 * only the bullets and no sentence appears twice on the page.
 */
export function splitHighlights(highlights: string) {
  const paragraphs = highlights.split("\n\n");
  const lead = paragraphs[0]?.trimStart().startsWith("-") ? undefined : paragraphs[0]?.trim();
  const body = (lead === undefined ? paragraphs : paragraphs.slice(1)).join("\n\n").trim();
  return { ...(lead ? { lead } : {}), ...(body ? { body } : {}) };
}

/**
 * Choose the editorial summary for a series.
 *
 * Prefers the hand-authored overlay, then the lead paragraph of the newest `### Highlights` block.
 * Returns `undefined` when neither exists so callers can fall back to a factual description rather
 * than promoting an arbitrary bullet into the page description.
 */
export function seriesSummary(series: ReleaseSeries, notes: SeriesNotes | undefined) {
  if (notes?.summary) {
    return notes.summary;
  }
  for (const release of series.releases) {
    const lead = release.highlights ? splitHighlights(release.highlights).lead : undefined;
    if (lead) {
      return toPlainText(lead);
    }
  }
  return undefined;
}

/** Describe a series' published span as a single phrase, or `undefined` when no release is dated. */
function seriesSpan(series: ReleaseSeries, dates: Record<string, string>) {
  const published = series.releases
    .filter((release) => !release.prerelease && dates[release.version])
    .map((release) => dates[release.version] as string);
  const newest = published[0];
  const oldest = published.at(-1);
  if (!newest || !oldest) {
    return undefined;
  }
  return oldest === newest ? formatDate(newest) : `${formatDate(oldest)} – ${formatDate(newest)}`;
}

/** Build a factual description for a series with no hand-authored or changelog-authored summary. */
function factualSummary(series: ReleaseSeries, dates: Record<string, string>) {
  const count = series.releases.filter((release) => !release.prerelease).length;
  const span = seriesSpan(series, dates);
  const releases = `${count} release${count === 1 ? "" : "s"}`;
  return span
    ? `Release notes for Hunk ${series.minor}: ${releases}, ${span}.`
    : `Release notes for Hunk ${series.minor}: ${releases}.`;
}

/** Resolve the summary a series page and index entry share. */
export function resolveSummary(
  series: ReleaseSeries,
  notes: SeriesNotes | undefined,
  dates: Record<string, string>,
) {
  return seriesSummary(series, notes) ?? factualSummary(series, dates);
}

/** Render one bullet, appending its pull-request link when the entry carries one. */
function renderEntry(entry: ChangeEntry) {
  const suffix =
    entry.pullRequest === undefined
      ? ""
      : ` ([#${entry.pullRequest}](${REPO_URL}/pull/${entry.pullRequest}))`;
  return `- ${entry.description}${suffix}`;
}

/** Render the self-hosted release video, including the schema search engines index it by. */
function renderVideo(video: NonNullable<SeriesNotes["video"]>, minor: string, summary: string) {
  const schema = {
    "@context": "https://schema.org",
    "@type": "VideoObject",
    name: video.title ?? `What's new in Hunk ${minor}`,
    description: summary,
    contentUrl: video.mp4,
    ...(video.poster ? { thumbnailUrl: `${SITE_ORIGIN}${video.poster}` } : {}),
    ...(video.duration ? { duration: video.duration } : {}),
  };

  const sources = [
    video.webm ? `    <source src="${video.webm}" type="video/webm" />` : undefined,
    `    <source src="${video.mp4}" type="video/mp4" />`,
  ].filter(Boolean);

  return [
    `<video class="changelog-video" controls preload="none"${video.poster ? ` poster="${video.poster}"` : ""}>`,
    ...sources,
    "  </video>",
    "",
    `<script type="application/ld+json" is:inline>${JSON.stringify(schema)}</script>`,
  ].join("\n");
}

/** Render one minor-series page. */
export function renderSeriesPage({
  series,
  notes,
  dates,
  newer,
  older,
  latestReleasedVersion,
}: {
  series: ReleaseSeries;
  notes: SeriesNotes | undefined;
  dates: Record<string, string>;
  newer?: string;
  older?: string;
  latestReleasedVersion?: string;
}) {
  const summary = resolveSummary(series, notes, dates);
  const newestHighlights = series.releases.find((release) => release.highlights)?.highlights;
  const highlightBullets = newestHighlights ? splitHighlights(newestHighlights).body : undefined;
  // Only offer an install command for a version that is actually published; the page can be
  // generated from a release-preparation branch before its tag and npm publication exist.
  const installable = series.releases.find(
    (release) => !release.prerelease && dates[release.version],
  )?.version;
  const isCurrent = latestReleasedVersion !== undefined && installable === latestReleasedVersion;

  const lines: string[] = [
    "---",
    `title: Hunk ${series.minor}`,
    `description: ${yamlString(truncate(toPlainText(summary), 155))}`,
    // Astro slugifies the filename and would drop the dot, publishing `0.18` as `/changelog/018/`.
    `slug: changelog/${series.minor}`,
    "---",
    "",
    GENERATED_NOTICE,
    "",
    summary,
    "",
  ];

  if (notes?.video) {
    lines.push(renderVideo(notes.video, series.minor, toPlainText(summary)), "");
  }

  if (installable) {
    lines.push(
      "```sh",
      `npm i -g hunkdiff@${installable}`,
      "```",
      "",
      isCurrent
        ? "This is the current release. See [all install options](/docs/start/install/)."
        : `Hunk ${series.minor} is no longer the current release. See [the latest release](/changelog/) or [all install options](/docs/start/install/).`,
      "",
    );
  }

  if (highlightBullets) {
    lines.push("## Highlights", "", highlightBullets, "");
  }

  if (notes?.links?.length) {
    lines.push(
      "## Related documentation",
      "",
      ...notes.links.map((link) => `- [${link.label}](${link.href})`),
      "",
    );
  }

  lines.push("## Releases in this series", "");

  for (const release of series.releases) {
    const date = dates[release.version];
    const meta = [
      date ? formatDate(date) : "Unreleased",
      release.prerelease ? "prerelease" : undefined,
    ]
      .filter(Boolean)
      .join(" · ");

    // Astro derives `#0182` from the heading text. Emit a stable, readable anchor beside it so a
    // single patch release can be linked from an issue, a release body, or the update notice.
    lines.push(
      `<a id="${versionAnchor(release.version)}"></a>`,
      "",
      `### ${release.version}`,
      "",
      meta,
      "",
    );

    if (release.sections.length === 0) {
      lines.push("No user-facing changes.", "");
      continue;
    }

    for (const section of release.sections) {
      lines.push(`#### ${section.title}`, "", ...section.entries.map(renderEntry), "");
    }
  }

  const around = [
    newer ? `[Newer: Hunk ${newer}](/changelog/${newer}/)` : undefined,
    older ? `[Older: Hunk ${older}](/changelog/${older}/)` : undefined,
    "[All releases](/changelog/)",
  ].filter(Boolean);
  lines.push("---", "", around.join(" · "), "");

  return `${lines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
}

/** Render the `/changelog/` index covering every series. */
export function renderIndexPage({
  seriesList,
  notes,
  dates,
}: {
  seriesList: readonly ReleaseSeries[];
  notes: Record<string, SeriesNotes>;
  dates: Record<string, string>;
}) {
  const lines: string[] = [
    "---",
    "title: Changelog",
    "description: " +
      yamlString(
        "Every Hunk release, newest first — features, fixes, and performance work in the terminal diff viewer.",
      ),
    "tableOfContents: false",
    "---",
    "",
    GENERATED_NOTICE,
    "",
    "Every Hunk release, newest first. Each page collects a whole minor series, so one page covers",
    `a release and every patch that followed it. Subscribe with [RSS](${SITE_ORIGIN}/changelog/rss.xml),`,
    `or read the raw source in [CHANGELOG.md](${REPO_URL}/blob/main/CHANGELOG.md).`,
    "",
  ];

  // "Latest" tracks the newest *published* series, not the newest heading in CHANGELOG.md: a
  // release-preparation branch adds its section before the tag exists, and that series is
  // unreleased until the tag date lands.
  const latestPublished = seriesList.find((series) =>
    series.releases.some((release) => !release.prerelease && dates[release.version]),
  )?.minor;

  seriesList.forEach((series) => {
    // Only an editorial summary earns a paragraph here; the factual fallback would just restate
    // the release count and date span already shown on the meta line below.
    const summary = seriesSummary(series, notes[series.minor]);
    const versions = series.releases.filter((release) => !release.prerelease);
    const published = seriesSpan(series, dates) !== undefined;

    const span = seriesSpan(series, dates);
    const changeCount = series.releases.reduce(
      (total, release) =>
        total + release.sections.reduce((count, section) => count + section.entries.length, 0),
      0,
    );
    const meta = [
      series.minor === latestPublished ? "Latest" : undefined,
      published ? undefined : "Unreleased",
      span,
      `${versions.length} release${versions.length === 1 ? "" : "s"}`,
      `${changeCount} change${changeCount === 1 ? "" : "s"}`,
    ]
      .filter(Boolean)
      .join(" · ");

    lines.push(
      `## [Hunk ${series.minor}](/changelog/${series.minor}/)`,
      "",
      meta,
      "",
      ...(summary ? [truncate(toPlainText(summary), 240), ""] : []),
    );
  });

  return `${lines
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trimEnd()}\n`;
}

/** Escape text for inclusion in an XML text node or attribute. */
function xmlEscape(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;");
}

/**
 * Render the RSS feed.
 *
 * One item per released minor series, dated by its newest published release, so subscribers see
 * one entry per meaningful release rather than one per patch.
 */
export function renderFeed({
  seriesList,
  notes,
  dates,
}: {
  seriesList: readonly ReleaseSeries[];
  notes: Record<string, SeriesNotes>;
  dates: Record<string, string>;
}) {
  const items = seriesList
    .map((series) => {
      const dated = series.releases
        .filter((release) => !release.prerelease && dates[release.version])
        .map((release) => ({ release, date: dates[release.version] as string }));
      const newest = dated[0];
      if (!newest) {
        return undefined;
      }
      const link = `${SITE_ORIGIN}/changelog/${series.minor}/`;
      const summary = truncate(
        toPlainText(resolveSummary(series, notes[series.minor], dates)),
        400,
      );
      return [
        "    <item>",
        `      <title>Hunk ${xmlEscape(series.minor)}</title>`,
        `      <link>${link}</link>`,
        `      <guid isPermaLink="true">${link}</guid>`,
        `      <pubDate>${new Date(`${newest.date}T00:00:00Z`).toUTCString()}</pubDate>`,
        `      <description>${xmlEscape(summary)}</description>`,
        "    </item>",
      ].join("\n");
    })
    .filter((item): item is string => item !== undefined);

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">',
    "  <channel>",
    "    <title>Hunk releases</title>",
    `    <link>${SITE_ORIGIN}/changelog/</link>`,
    "    <description>Release notes for Hunk, the review-first terminal diff viewer.</description>",
    "    <language>en</language>",
    `    <atom:link href="${SITE_ORIGIN}/changelog/rss.xml" rel="self" type="application/rss+xml" />`,
    ...items,
    "  </channel>",
    "</rss>",
    "",
  ].join("\n");
}

/** Produce every committed changelog artifact, keyed by absolute path. */
export function generateChangelogArtifacts({
  markdown = readFileSync(CHANGELOG_SOURCE, "utf8"),
  notes = readNotes(),
  recordedDates = readDates(),
  lookupDate = tagDate,
}: {
  markdown?: string;
  notes?: Record<string, SeriesNotes>;
  recordedDates?: Record<string, string>;
  lookupDate?: (version: string) => string | undefined;
} = {}) {
  const releases = parseChangelog(markdown);
  const dates = resolveDates(releases, recordedDates, lookupDate);
  const seriesList = groupIntoSeries(releases);
  const latestReleasedVersion = releases.find(
    (release) => !release.prerelease && dates[release.version],
  )?.version;

  // The landing page reads this rather than the pages themselves, so its release ribbon stays a
  // static import instead of a build-time parse of generated Markdown.
  const latestSeries = latestReleasedVersion
    ? seriesList.find((series) => series.minor === minorSeriesOf(latestReleasedVersion))
    : undefined;
  const latest = latestSeries
    ? {
        version: latestReleasedVersion,
        minor: latestSeries.minor,
        date: dates[latestReleasedVersion as string],
        summary:
          notes[latestSeries.minor]?.tagline ??
          truncate(toPlainText(resolveSummary(latestSeries, notes[latestSeries.minor], dates)), 72),
      }
    : null;

  const artifacts: Record<string, string> = {
    [RELEASE_DATES_SOURCE]: `${JSON.stringify(dates, null, 2)}\n`,
    [LATEST_RELEASE_PATH]: `${JSON.stringify(latest, null, 2)}\n`,
    [resolve(CHANGELOG_OUTPUT_DIR, "index.md")]: renderIndexPage({ seriesList, notes, dates }),
    [CHANGELOG_FEED_PATH]: renderFeed({ seriesList, notes, dates }),
  };

  seriesList.forEach((series, index) => {
    artifacts[resolve(CHANGELOG_OUTPUT_DIR, `${series.minor}.md`)] = renderSeriesPage({
      series,
      notes: notes[series.minor],
      dates,
      ...(seriesList[index - 1] ? { newer: seriesList[index - 1]?.minor } : {}),
      ...(seriesList[index + 1] ? { older: seriesList[index + 1]?.minor } : {}),
      ...(latestReleasedVersion ? { latestReleasedVersion } : {}),
    });
  });

  return artifacts;
}

/** List generated series pages that no longer correspond to a series in `CHANGELOG.md`. */
function findOrphanedPages(artifacts: Readonly<Record<string, string>>) {
  let existing: string[];
  try {
    existing = readdirSync(CHANGELOG_OUTPUT_DIR);
  } catch {
    return [];
  }
  return existing
    .filter((name) => name.endsWith(".md"))
    .map((name) => resolve(CHANGELOG_OUTPUT_DIR, name))
    .filter((path) => !(path in artifacts));
}

/** Write generated artifacts, or report stale paths without modifying them. */
export function updateGeneratedChangelog({
  check = false,
  artifacts = generateChangelogArtifacts(),
}: {
  check?: boolean;
  artifacts?: Readonly<Record<string, string>>;
} = {}) {
  const stalePaths: string[] = [];

  for (const path of findOrphanedPages(artifacts)) {
    stalePaths.push(path);
    if (!check) {
      rmSync(path);
    }
  }

  for (const [path, content] of Object.entries(artifacts)) {
    const current = (() => {
      try {
        return readFileSync(path, "utf8");
      } catch {
        return undefined;
      }
    })();
    if (current === content) {
      continue;
    }
    stalePaths.push(path);
    if (!check) {
      mkdirSync(resolve(path, ".."), { recursive: true });
      writeFileSync(path, content);
    }
  }

  return stalePaths;
}

if (import.meta.main) {
  const check = process.argv.includes("--check");
  const stalePaths = updateGeneratedChangelog({ check });
  if (check && stalePaths.length > 0) {
    console.error("Generated changelog pages are stale:");
    for (const path of stalePaths) {
      console.error(`  ${path}`);
    }
    console.error("Run `bun run generate:changelog` and commit the result.");
    process.exit(1);
  }
  if (!check) {
    console.log(
      stalePaths.length > 0
        ? `Updated ${stalePaths.length} generated changelog file(s).`
        : "Generated changelog is already current.",
    );
  }
}
