export const BUNDLED_SHIKI_THEME_IDS = [
  "andromeeda",
  "aurora-x",
  "ayu-dark",
  "ayu-light",
  "ayu-mirage",
  "catppuccin-frappe",
  "catppuccin-latte",
  "catppuccin-macchiato",
  "catppuccin-mocha",
  "dark-plus",
  "dracula",
  "dracula-soft",
  "everforest-dark",
  "everforest-light",
  "github-dark",
  "github-dark-default",
  "github-dark-dimmed",
  "github-dark-high-contrast",
  "github-light",
  "github-light-default",
  "github-light-high-contrast",
  "gruvbox-dark-hard",
  "gruvbox-dark-medium",
  "gruvbox-dark-soft",
  "gruvbox-light-hard",
  "gruvbox-light-medium",
  "gruvbox-light-soft",
  "horizon",
  "horizon-bright",
  "houston",
  "kanagawa-dragon",
  "kanagawa-lotus",
  "kanagawa-wave",
  "laserwave",
  "light-plus",
  "material-theme",
  "material-theme-darker",
  "material-theme-lighter",
  "material-theme-ocean",
  "material-theme-palenight",
  "min-dark",
  "min-light",
  "monokai",
  "night-owl",
  "night-owl-light",
  "nord",
  "one-dark-pro",
  "one-light",
  "plastic",
  "poimandres",
  "red",
  "rose-pine",
  "rose-pine-dawn",
  "rose-pine-moon",
  "slack-dark",
  "slack-ochin",
  "snazzy-light",
  "solarized-dark",
  "solarized-light",
  "synthwave-84",
  "tokyo-night",
  "vesper",
  "vitesse-black",
  "vitesse-dark",
  "vitesse-light",
] as const;

export type BundledShikiThemeId = (typeof BUNDLED_SHIKI_THEME_IDS)[number];

export const BUNDLED_SHIKI_THEME_BACKGROUNDS: Record<BundledShikiThemeId, string> = {
  andromeeda: "#23262e",
  "aurora-x": "#07090f",
  "ayu-dark": "#10141c",
  "ayu-light": "#fcfcfc",
  "ayu-mirage": "#242936",
  "catppuccin-frappe": "#303446",
  "catppuccin-latte": "#eff1f5",
  "catppuccin-macchiato": "#24273a",
  "catppuccin-mocha": "#1e1e2e",
  "dark-plus": "#1e1e1e",
  dracula: "#282a36",
  "dracula-soft": "#282a36",
  "everforest-dark": "#2d353b",
  "everforest-light": "#fdf6e3",
  "github-dark": "#24292e",
  "github-dark-default": "#0d1117",
  "github-dark-dimmed": "#22272e",
  "github-dark-high-contrast": "#0a0c10",
  "github-light": "#ffffff",
  "github-light-default": "#ffffff",
  "github-light-high-contrast": "#ffffff",
  "gruvbox-dark-hard": "#1d2021",
  "gruvbox-dark-medium": "#282828",
  "gruvbox-dark-soft": "#32302f",
  "gruvbox-light-hard": "#f9f5d7",
  "gruvbox-light-medium": "#fbf1c7",
  "gruvbox-light-soft": "#f2e5bc",
  horizon: "#1c1e26",
  "horizon-bright": "#fdf0ed",
  houston: "#17191e",
  "kanagawa-dragon": "#181616",
  "kanagawa-lotus": "#f2ecbc",
  "kanagawa-wave": "#1f1f28",
  laserwave: "#27212e",
  "light-plus": "#ffffff",
  "material-theme": "#263238",
  "material-theme-darker": "#212121",
  "material-theme-lighter": "#fafafa",
  "material-theme-ocean": "#0f111a",
  "material-theme-palenight": "#292d3e",
  "min-dark": "#1f1f1f",
  "min-light": "#ffffff",
  monokai: "#272822",
  "night-owl": "#011627",
  "night-owl-light": "#fbfbfb",
  nord: "#2e3440",
  "one-dark-pro": "#282c34",
  "one-light": "#fafafa",
  plastic: "#21252b",
  poimandres: "#1b1e28",
  red: "#390000",
  "rose-pine": "#191724",
  "rose-pine-dawn": "#faf4ed",
  "rose-pine-moon": "#232136",
  "slack-dark": "#222222",
  "slack-ochin": "#ffffff",
  "snazzy-light": "#fafbfc",
  "solarized-dark": "#002b36",
  "solarized-light": "#fdf6e3",
  "synthwave-84": "#262335",
  "tokyo-night": "#1a1b26",
  vesper: "#101010",
  "vitesse-black": "#000000",
  "vitesse-dark": "#121212",
  "vitesse-light": "#ffffff",
};

/** Return the editor surface declared by a bundled Shiki theme, when Hunk knows it. */
export function getBundledShikiThemeBackground(themeId: string | undefined) {
  return themeId && themeId in BUNDLED_SHIKI_THEME_BACKGROUNDS
    ? BUNDLED_SHIKI_THEME_BACKGROUNDS[themeId as BundledShikiThemeId]
    : undefined;
}
