export const BUNDLED_SHIKI_THEME_IDS = [
  "andromeeda",
  "aurora-x",
  "ayu-dark",
  "ayu-light",
  "ayu-mirage",
  "catppuccin-frappe",
  "catppuccin-latte",
  "catppuccin-macchiato",
  "catppuccin-mocha",
  "dark-plus",
  "dracula",
  "dracula-soft",
  "everforest-dark",
  "everforest-light",
  "github-dark",
  "github-dark-default",
  "github-dark-dimmed",
  "github-dark-high-contrast",
  "github-light",
  "github-light-default",
  "github-light-high-contrast",
  "gruvbox-dark-hard",
  "gruvbox-dark-medium",
  "gruvbox-dark-soft",
  "gruvbox-light-hard",
  "gruvbox-light-medium",
  "gruvbox-light-soft",
  "horizon",
  "horizon-bright",
  "houston",
  "kanagawa-dragon",
  "kanagawa-lotus",
  "kanagawa-wave",
  "laserwave",
  "light-plus",
  "material-theme",
  "material-theme-darker",
  "material-theme-lighter",
  "material-theme-ocean",
  "material-theme-palenight",
  "min-dark",
  "min-light",
  "monokai",
  "night-owl",
  "night-owl-light",
  "nord",
  "one-dark-pro",
  "one-light",
  "plastic",
  "poimandres",
  "red",
  "rose-pine",
  "rose-pine-dawn",
  "rose-pine-moon",
  "slack-dark",
  "slack-ochin",
  "snazzy-light",
  "solarized-dark",
  "solarized-light",
  "synthwave-84",
  "tokyo-night",
  "vesper",
  "vitesse-black",
  "vitesse-dark",
  "vitesse-light",
] as const;

export type BundledShikiThemeId = (typeof BUNDLED_SHIKI_THEME_IDS)[number];

export const BUNDLED_SHIKI_THEME_BACKGROUNDS: Record<BundledShikiThemeId, string> = {
  andromeeda: "#23262e",
  "aurora-x": "#07090f",
  "ayu-dark": "#10141c",
  "ayu-light": "#fcfcfc",
  "ayu-mirage": "#242936",
  "catppuccin-frappe": "#303446",
  "catppuccin-latte": "#eff1f5",
  "catppuccin-macchiato": "#24273a",
  "catppuccin-mocha": "#1e1e2e",
  "dark-plus": "#1e1e1e",
  dracula: "#282a36",
  "dracula-soft": "#282a36",
  "everforest-dark": "#2d353b",
  "everforest-light": "#fdf6e3",
  "github-dark": "#24292e",
  "github-dark-default": "#0d1117",
  "github-dark-dimmed": "#22272e",
  "github-dark-high-contrast": "#0a0c10",
  "github-light": "#ffffff",
  "github-light-default": "#ffffff",
  "github-light-high-contrast": "#ffffff",
  "gruvbox-dark-hard": "#1d2021",
  "gruvbox-dark-medium": "#282828",
  "gruvbox-dark-soft": "#32302f",
  "gruvbox-light-hard": "#f9f5d7",
  "gruvbox-light-medium": "#fbf1c7",
  "gruvbox-light-soft": "#f2e5bc",
  horizon: "#1c1e26",
  "horizon-bright": "#fdf0ed",
  houston: "#17191e",
  "kanagawa-dragon": "#181616",
  "kanagawa-lotus": "#f2ecbc",
  "kanagawa-wave": "#1f1f28",
  laserwave: "#27212e",
  "light-plus": "#ffffff",
  "material-theme": "#263238",
  "material-theme-darker": "#212121",
  "material-theme-lighter": "#fafafa",
  "material-theme-ocean": "#0f111a",
  "material-theme-palenight": "#292d3e",
  "min-dark": "#1f1f1f",
  "min-light": "#ffffff",
  monokai: "#272822",
  "night-owl": "#011627",
  "night-owl-light": "#fbfbfb",
  nord: "#2e3440",
  "one-dark-pro": "#282c34",
  "one-light": "#fafafa",
  plastic: "#21252b",
  poimandres: "#1b1e28",
  red: "#390000",
  "rose-pine": "#191724",
  "rose-pine-dawn": "#faf4ed",
  "rose-pine-moon": "#232136",
  "slack-dark": "#222222",
  "slack-ochin": "#ffffff",
  "snazzy-light": "#fafbfc",
  "solarized-dark": "#002b36",
  "solarized-light": "#fdf6e3",
  "synthwave-84": "#262335",
  "tokyo-night": "#1a1b26",
  vesper: "#101010",
  "vitesse-black": "#000000",
  "vitesse-dark": "#121212",
  "vitesse-light": "#ffffff",
};

export const BUNDLED_SHIKI_THEME_FOREGROUNDS: Partial<Record<BundledShikiThemeId, string>> = {
  andromeeda: "#d5ced9",
  "ayu-dark": "#bfbdb6",
  "ayu-light": "#5c6166",
  "ayu-mirage": "#cccac2",
  "catppuccin-frappe": "#c6d0f5",
  "catppuccin-latte": "#4c4f69",
  "catppuccin-macchiato": "#cad3f5",
  "catppuccin-mocha": "#cdd6f4",
  "dark-plus": "#d4d4d4",
  dracula: "#f8f8f2",
  "dracula-soft": "#f6f6f4",
  "everforest-dark": "#d3c6aa",
  "everforest-light": "#5c6a72",
  "github-dark": "#e1e4e8",
  "github-dark-default": "#e6edf3",
  "github-dark-dimmed": "#adbac7",
  "github-dark-high-contrast": "#f0f3f6",
  "github-light": "#24292e",
  "github-light-default": "#1f2328",
  "github-light-high-contrast": "#0e1116",
  "gruvbox-dark-hard": "#ebdbb2",
  "gruvbox-dark-medium": "#ebdbb2",
  "gruvbox-dark-soft": "#ebdbb2",
  "gruvbox-light-hard": "#3c3836",
  "gruvbox-light-medium": "#3c3836",
  "gruvbox-light-soft": "#3c3836",
  houston: "#eef0f9",
  "kanagawa-dragon": "#c5c9c5",
  "kanagawa-lotus": "#545464",
  "kanagawa-wave": "#dcd7ba",
  laserwave: "#ffffff",
  "light-plus": "#000000",
  "material-theme": "#eeffff",
  "material-theme-darker": "#eeffff",
  "material-theme-lighter": "#90a4ae",
  "material-theme-ocean": "#babed8",
  "material-theme-palenight": "#babed8",
  "min-light": "#212121",
  monokai: "#f8f8f2",
  "night-owl": "#d6deeb",
  "night-owl-light": "#403f53",
  nord: "#d8dee9",
  "one-dark-pro": "#abb2bf",
  "one-light": "#383a42",
  plastic: "#a9b2c3",
  poimandres: "#a6accd",
  red: "#f8f8f8",
  "rose-pine": "#e0def4",
  "rose-pine-dawn": "#575279",
  "rose-pine-moon": "#e0def4",
  "slack-dark": "#e6e6e6",
  "slack-ochin": "#000000",
  "snazzy-light": "#565869",
  "solarized-dark": "#839496",
  "solarized-light": "#657b83",
  "tokyo-night": "#a9b1d6",
  vesper: "#ffffff",
  "vitesse-black": "#dbd7ca",
  "vitesse-dark": "#dbd7ca",
  "vitesse-light": "#393a34",
};

/** Return the editor surface declared by a bundled Shiki theme, when Hunk knows it. */
export function getBundledShikiThemeBackground(themeId: string | undefined) {
  return themeId && themeId in BUNDLED_SHIKI_THEME_BACKGROUNDS
    ? BUNDLED_SHIKI_THEME_BACKGROUNDS[themeId as BundledShikiThemeId]
    : undefined;
}

/** Return the editor foreground declared by a bundled Shiki theme, when Hunk knows it. */
export function getBundledShikiThemeForeground(themeId: string | undefined) {
  return themeId && themeId in BUNDLED_SHIKI_THEME_FOREGROUNDS
    ? BUNDLED_SHIKI_THEME_FOREGROUNDS[themeId as BundledShikiThemeId]
    : undefined;
}
